development:
  host: localhost
  database: db_name
  username: db_user
  password: 'db_pass'
staging:
  host: localhost
  database: db_name
  username: db_user
  password: 'db_pass'
production:
  host: localhost
  database: db_name
  username: db_user
  password: 'db_pass'
